config/routes.rb
Rails.application.routes.draw do
  resources :userprojects

  resources :performs

  resources :contacts 

  resources :cities do 
    collection do
      get 'tehran'
      get 'esfahan'
      get 'ghom'
      get 'gilan'
      get 'golestan'
      get 'mazandaran'
      get 'kerman'
      get 'kermanshah'
      get 'azarbayjansharghi'
      get 'azarbayjangharbi'
      get 'ardebil'
      get 'eilam'
      get 'boushehr'
      get 'charmahalebakhtiari'
      get 'khorasanjounubi'
      get 'khorasanshomali'
      get 'khorasanrazavi'
      get 'khuzestan'
      get 'zanjan'
      get 'systanvabalouchestan'
      get 'semnan'
      get 'fars'
      get 'ghazvin'
      get 'kohgiluyevabayerahmad'
      get 'kordestan'
      get 'lorestan'
      get 'markazi'
      get 'hormozgan'
      get 'hamedan'
      get 'yazd'
      get 'alborz'
    end
  end

  devise_for :users

  resources :reports do
    collection do
      get 'reportbarayeproject'
    end
  end

  resources :profiles do
    collection do
      get 'mannagers'
      get 'ourprojects'
      get 'memari'
      get 'saze'
      get 'tasisat'
      get 'mohitezist'
      get 'tamasbama'
      get 'darbareyema'
      get 'taghdirname'
      get 'projehabarayesherkat'
      get 'newUser'
      post 'addUser'
      get 'editUser'
      put 'updateUser'
      patch 'updateUser'
    end
  end

  resources :profiles

  resources :projects
  resources :example_mailers

  root 'profiles#homepage'

  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # load_and_authorize_resource :except => :homepage
  before_action :authenticate_user! , :except => [:mannagers, :ourprojects ,  :homepage , :memari , :saze , :tasisat,:taghdirname,:darbareyema ,:tamasbama ,:mohitezist]
  before_action :set_profile, only: [:show, :edit, :update, :destroy , :addUser , :editUser]
  before_action :check_admin , only: [:addUser]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = current_user
    @projects = Project.all 
    @user = current_user
  end

  def newUser
    @user = User.new
  end

  # GET /profile/editUser
  def editUser
    @user = current_user
  end

  #post /profile/updateUser
  def updateUser
    @user = current_user
    respond_to do |format|
      if @user.valid_password?(user_update_params[:current_password])
        params[:user].delete :current_password

        byebug
        if @user.update(user_update_params)
          format.html { redirect_to url_for(:action=>'show', :controller=>'profiles' , :id => current_user.id), notice: 'Profile was successfully updated.' }
          format.json { render :show, status: :ok, location: url_for(:action=>'show', :controller=>'profiles' , :id => current_user.profile.id) }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html {redirect_to url_for(:action=>'editUser' , :controller=>'profiles') , notice: 'Your current password is wrong'}
      end
    end
  end

  def addUser

    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_url, notice: 'user was successfully created.' }
      else
        format.html { render :newUser }
      end
    end

  end
  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mannagers
  end

  def ourprojects
  end


  def memari
  end

  def saze
  end

  def tasisat
  end

  def tamasbama
    redirect_to "contacts/new"
  end

  def darbareyema
  end

  def taghdirname
  end

  def projehabarayesherkat
  end

  def mohitezist
  end

  def download
    send_file(@filename, :filename => "Binder1 opt.pdf")
  end

  private
    def check_admin
      unless current_user.role ==  "ادمین"
        redirect_to root_url
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company_name, :work_experience, :register_number, :tel, :fax, :image , :avatar , :user_id)
    end
    def user_params
      params.require(:user).permit(:email, :password_confirmation, :password, :role ,:company_name , :work_experience ,:avatar, :register_number , :tel ,:fax)
    end

    def user_update_params
      params.require(:user).permit(:email, :password_confirmation, :password, :role ,:company_name , :work_experience ,:avatar, :register_number , :tel ,:fax,:current_password)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
  <div class="col-mod-7">
      <div class="portlet box purple" style="margin-left:25%;margin-right:25%;margin-top:15%;">
                      <div class="portlet-title">
                        <div class="caption" style="margin-left:40%;" >
                          فرم ایجاد پروفایل
                        </div> 
                        <div class="tools">
                          <a href="javascript:;" class="collapse" data-original-title="" title="">
                          </a>
                          <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
                          </a>
                          <a href="javascript:;" class="reload" data-original-title="" title="">
                          </a>
                          <a href="javascript:;" class="remove" data-original-title="" title="">
                          </a>
                        </div>
                      </div>
                      <div class="portlet-body form">
                        <!-- BEGIN FORM-->
                        <%form_for Profile.new do |f|%>
                        
                          <% if @profile.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

                              <ul>
                              <% @profile.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>
                        <!-- <form > -->
                          <div class="form-body">
                            <div class="form-group">
                              <label class="control-label">نام شرکت</label>
                              <%= f.text_field :company_name , class: "form-control"  ,placeholder:"نام شرکت" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                              <label class="control-label">سابقه کاری</label>
                              <%= f.number_field :work_experience , class: "form-control"  ,placeholder:"سابقه کاری" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                              <label class="control-label">شماره ثبت</label>
                              <%= f.number_field :register_number  , class: "form-control"  ,placeholder:"شماره ثبت" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                              <label class="control-label">شماره تلفن</label>
                              <%= f.text_field :tel , class: "form-control"  ,placeholder:"شماره تلفن" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                              <label class="control-label">شماره فکس</label>
                              <%= f.text_field :fax  , class: "form-control"  ,placeholder:"شماره فکس" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                              <label class="control-label" >عکس</label>
                              <%= f.file_field :avatar ,class: "form-control spinner" %>
                              <!-- <input type="password" class="form-control spinner" placeholder="Password"> -->
                            </div>
                            <!-- <div class="form-group last">
                              <label class="control-label">Static Control</label>
                              <p class="form-control-static">
                                 email@example.com
                              </p>
                            </div> -->
                          </div>
                          <div class="form-actions right">
                          <%= f.submit  %>
<!--                             <button type="submit" class="btn green">Submit</button>
                            <button type="button" class="btn default">Cancel</button> -->
                          </div>
                          <% end %>
                        <!-- </form> -->
                        <!-- END FORM-->
                      </div>
                      </div>
                    </div>

<div class="page-footer">
  <div class="page-footer-inner">
     2014 &copy; Metronic by keenthemes.
  </div>
  <div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
  </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../../assets/global/plugins/respond.min.js"></script>
<script src="../../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->
<!-- <script src="/assets/js-profile/jquery.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/jquery-migrate.min.js" type="text/javascript"></script> -->
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<!-- <script src="/assets/js-profile/jquery-ui.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/bootstrap.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/bootstrap-hover-dropdown.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/jquery.slimscroll.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/jquery.blockui.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/jquery.cokie.min.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/jquery.uniform.min.js" type="text/javascript"></script>
 --><!-- <script src="/assets/js-profile/bootstrap-switch.min.js" type="text/javascript"></script> -->
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- <script type="text/javascript" src="/assets/js-profile/select2.min.js"></script> -->
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<!-- <script src="/assets/js-profile/metronic.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/layout.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/demo.js" type="text/javascript"></script> -->
<!-- <script src="/assets/js-profile/form-samples.js"></script> -->
<!-- END PAGE LEVEL SCRIPTS -->
<script>
jQuery(document).ready(function() {    
   // initiate layout and plugins
   Metronic.init(); // init metronic core components
Layout.init(); // init current layout
Demo.init(); // init demo features
   FormSamples.init();
});
</script>

app/views/profiles/darbareyema.html.erb
    <div class="wrapper"  style="direction: rtl;">
<style type="text/css">
  @font-face {
  font-family: 'Pacifico';
  font-style: normal;
  font-weight: 400;
  src: local('Pacifico Regular'), local('Pacifico-Regular'), url(http://fonts.gstatic.com/s/pacifico/v7/yunJt0R8tCvMyj_V4xSjafesZW2xOQ-xsNqO47m55DA.woff) format('woff');
}

</style>
              <h1 style="color:blue;    padding-right: 4%;"> درباره ما</h1>
               <p style="padding:4%;font-size: 120%;text-align: justify;line-height: 26px;margin-bottom:-7%;margin-top:-4%;"><font color="black" family="BNazanin">
              شركت مهندسين مشاور معماري و محيط درسال 1360 به منظور ارائه خدمات مشاوره‌اي فني درزمينه پروژه‌هاي معماري و شهرسازي تأسیس و با تأييد سازمان برنامه و بودجه وقت به عنوان مهندس مشاور در رشته معماري و شهرسازي تشخيص صلاحيت شده و هم اكنون در رشته ساختمان با گرايش ساختمان‌هاي آموزشی–  ورزشی –  بهداشتی – درمانی ، مسکونی –  اداری – تجاری – صنعتی و نظامی و مقاوم‌سازی  فعاليت مي نمايد. 
              </br></br>
              مهندسين مشاور معماري و محيط در طي بيش از 30 سال فعاليت اين توفيق را داشته تا علاوه برمسئوليت تهيه طرح و نظارت بر اجراي بسياري از پروژه‌ها آموزشي، اداري، مسكوني و خدماتي مربوط به سازمان‌هاي دولتي و با شهرداري‌ها درتهيه طرح‌هاي جامع شهري و دانشگاهي و برنامه‌ريزي‌هاي مختلف نيز پروژه‌اي را به مرحله بهره برداري برساند.
              </br>
              در حال حاضر آقایان سعید ایمنی (با 38 سال سابقه) سمت مدیریت عاملی شرکت و سرپرستی بخش سازه و یزدان هوشور (با 51 سال سابقه) سمت نایب رئیس هیئت مدیره و سرپرستی بخش معماری شرکت را بر عهده دارند و سرکار خانم خوبچهر کشاورزی (با 45 سال سابقه) رئیس هیئت مدیرۀ شرکت می‌باشند.
              </br>
              مهندسين مشاورمعماري و محيط آمادگي كامل دارد تا درانجام كليه امورطراحي ونظارت پروژه‌هاي ساختماني خدمات مهندسي ارائه نمايد.
             </font></p>
              <a class="action-button shadow animate green"  href="/Binder1 opt.pdf"> <b> دریافت رزومه شرکت  </b> </a>
            </div>
                

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

  <h1 style="margin-right:5%">لیست پروفایل ها</h1>

<div class="col-xs-12">
                <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th>
                     نام شرکت
                  </th>
                  <th>
                     سابقه کاری
                  </th>
                  <th >
                     شماره ثبت
                  </th>
                  <th >
                     شماره تلفن
                  </th>
                  <th >
                     شماره فکس
                  </th>
                  <th >
                     عکس
                  </th>
                 
                </tr>
                </thead>

                <tbody>
                <tr>
              <% @profiles.each do |profile| %>
                <tr>
                <th ><%= profile.company_name  %></td>
                <th ><%= profile.work_experience  %></td>
                <th ><%= profile.register_number%></td>
                <th ><%= profile.tel%></td>
                <th ><%= profile.fax %></td>
                <th ><%= image_tag profile.avatar.url , style:"width:16%;height:26%;"%></td>
                <th ><%= link_to 'جزئيات بیشتر', profile , class:"btn btn-sh green hidden-print margin-bottom-5"%></td>
                <th ><%= link_to 'ویرایش', edit_profile_path(profile) , class:"btn btn-sh blue hidden-print margin-bottom-5" %></td>
                <th ><%= link_to 'حذف', profile, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-sh red hidden-print margin-bottom-5" %></td>
      </tr>
    <% end %>
                </tr>
                </tbody>
                </table>
              </div>


<br>

<%= link_to 'ایجاد پروفایل', new_profile_path ,class:"btn btn-sh green hidden-print margin-bottom-5",style:"margin-right:5%;margin-bottom:2%"%>
 <br><br><br><br><br><br>

app/views/profiles/mohitezist.html.erb
    <div class="wrapper">
  <ul class="tabs clearfix" data-tabgroup="first-tab-group">
    <li><a href="#tab1" class="active"><font color="black" family="BNazanin">فرشید ایمنی</font></a></li>
    <li><a href="#tab2"><font color="black" family="BNazanin">حمیده میروکیلی</font></a></li>
  </ul>
  <section id="first-tab-group" class="tabgroup">
    <div id="tab1">
      <div    style="direction: rtl;">
    <div style="text-align: center;">
      <div class="thumbnail" style="border:10px outset silver;height:420px;">
        <%= image_tag("profile.png") %>
        <!-- <img src="/assets/profiles_pic/profile.png" > -->
          <div class="caption">
            <h3><font color="black" family="BNazanin">فرشید ایمنی</font></h3>
             <font color="black" family="BNazanin">سابقه کار - سال : ۷
            <br>
              مدرک تحصیلی:کارشناس سازه / کارشناس ارشد محیط‌زیست
              <br>
       گروه:محیط زیست</font>
    </div>
        </div>
    </div>
  </div>
    </div>
    <div id="tab2">
      <div    style="direction: rtl;">
  <div style="text-align: center;">
    <div class="thumbnail" style="border:10px outset silver; height:420px;">
      <%= image_tag("profile.png") %>
      <!-- <img src="/assets/profiles_pic/profile.png" > -->
      <div class="caption">
        <h3><font color="black" family="BNazanin"> حمیده سادات میروکیلی </font></h3>
        <font color="black" family="BNazanin">سابقه کار - سال : ۸
        <br>
        مدرک تحصیلی:کارشناس سازه / کارشناس ارشد محیط‌زیست 
        <br>
        گروه:محیط زیست</font>
    </div>
  </div>
</div>
</div>
    </div>
    
  </section>
</div>
<div class="container">
            <div class="row wrap_9 wrap_4 wrap_10">
                <div class="grid_12">
                    <div class="header_1 wrap_3 color_3">
                        Get in Touch
                    </div>
                    <div class="box_3">
                        <ul class="list_1">
                            <li><a class="fa fa-twitter" href="#"></a></li>
                            <li><a class="fa fa-facebook" href="#"></a></li>
                            <li><a class="fa fa-google-plus" href="#"></a></li>
                            <li><a class="fa fa-pinterest" href="#"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <script >
        $('.tabgroup > div').hide();
$('.tabgroup > div:first-of-type').show();
$('.tabs a').click(function(e){
  e.preventDefault();
    var $this = $(this),
        tabgroup = '#'+$this.parents('.tabs').data('tabgroup'),
        others = $this.closest('li').siblings().children('a'),
        target = $this.attr('href');
    others.removeClass('active');
    $this.addClass('active');
    $(tabgroup).children('div').hide();
    $(target).show();
  
})</script>

app/views/profiles/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/ourprojects.html.erb
<div class="khar2">


	 <div class="wrapper">
	<embed src="/iran_map.swf" , style=" height:600px; width:600px;">
</div>
</div>

        <script >
        $('.tabgroup > div').hide();
$('.tabgroup > div:first-of-type').show();
$('.tabs a').click(function(e){
  e.preventDefault();
    var $this = $(this),
        tabgroup = '#'+$this.parents('.tabs').data('tabgroup'),
        others = $this.closest('li').siblings().children('a'),
        target = $this.attr('href');
    others.removeClass('active');
    $this.addClass('active');
    $(tabgroup).children('div').hide();
    $(target).show();
  
})</script>

app/views/profiles/projehabarayesherkat.html.erb
<p id="notice"><%= notice %></p>

  <h1 style="margin-right:5%">لیست پروژه</h1>

<div style="height:850px;">
                <table class="table table-striped table-hover">
                <thead>
                <tr>
                <th >
                     عکس
                  </th>
                 <th >
                     زمان پایان
                  </th>
                  <th>
                     زمان شروع
                  </th>
                  
                   <th>
                     نام پروژه ها
                  </th>
                 
                </tr>
                </thead>
        <tbody>
        <tr>
                <% current_user.projects.all.each do |project| %>
                <th ><%= project.name %></th>
                <th ><%= project.start_time %></th>
                <th ><%= project.end_time %></th>
                <th ><%= image_tag project.avatar.url , style:"width:16%;height:26%;"%></th>
                <th ><%= link_to 'جزئيات بیشتر', project , class:"btn btn-sh green hidden-print margin-bottom-5"%></th>
                <th ><%= link_to 'ویرایش', edit_project_path(project) , class:"btn btn-sh blue hidden-print margin-bottom-5" %></th>

                <th ><%= link_to 'گزارش ها', project, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-sh red hidden-print margin-bottom-5" %></th>
                
                        </tr>
                      <% end %>
            </tbody>
                

              </table>
              <%if not current_user.nil? and current_user.role == 'ناظر' %>
                <%= link_to 'ایجاد پروژه', new_project_path ,class:"action-button shadow animate green"%>
                  <%end%>

              </div>


<br>



<style>
  #page-wrap {
    align:right;
  margin: 50px;
  }


  /* 
  Generic Styling, for Desktops/Laptops 
  */
  #FU {
    margin-right: 10%;
  }
  table { 
    width: 100%; 
    border-collapse: collapse; 
  }
  /* Zebra striping */
  tr:nth-of-type(odd) { 
    background: #eee; 
  }
  th { 
    background: #333; 
    color: white; 
    font-weight: bold; 
  }
  td, th { 
    padding: 6px; 
    border: 1px solid #ccc; 
    text-align: right; 
  }
  /* 
  Max width before this PARTICULAR table gets nasty
  This query will take effect for any screen smaller than 760px
  and also iPads specifically.
  */
  @media 
  only screen and (max-width: 760px),
  (min-device-width: 768px) and (max-device-width: 1024px)  {
  
    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr { 
      display: block; 
    }
    
    /* Hide table headers (but not display: none;, for accessibility) */
    thead tr { 
      position: absolute;
      top: -9999px;
      left: -9999px;
    }
    
    tr { border: 1px solid #ccc; }
    
    td { 
      /* Behave  like a "row" */
      border: none;
      border-bottom: 1px solid #eee; 
      position: relative;
      padding-left: 50%; 
    }
    
    td:before { 
      /* Now like a table header */
      position: absolute;
      /* Top/left values mimic padding */
      top: 6px;
      left: 6px;
      width: 45%; 
      padding-right: 10px; 
      white-space: nowrap;
    }
    
    /*
    Label the data
    */
  
  }
  
  /* Smartphones (portrait and landscape) ----------- */
  @media only screen
  and (min-device-width : 320px)
  and (max-device-width : 480px) {

  
  /* iPads (portrait and landscape) ----------- */

  }
  
  </style>

app/views/profiles/show.html.erb
                            <div class="wrapper">
  <ul class="tabs clearfix" data-tabgroup="first-tab-group">
    <li><a href="#tab1" class="active">ویرایش پروفایل</a></li>
    <li><a href="#tab2">پروژه ها</a></li>
    <li><a href="#tab3">گزارش ها</a></li>
    <li><a href="#tab4">تماس با ما</a></li>
      </ul>

  <section id="first-tab-group" class="tabgroup">
    <div id="tab1">
      <div    style="direction: rtl;">
  <div style="text-align: center;">
    <div class="thumbnail" style="border:10px outset silver; height:420px;">
     <%=image_tag @current_user.avatar.url %>
     <br>
            <%= @current_user.company_name %>
      <div class="caption">
        <%= link_to "ویرایش پروفایل", editUser_profiles_path,:method => :get  %>
    </div>
  </div>
</div>
</div>
</div>
<div id="tab2">
      <div    style="direction: rtl;">
  <div style="text-align: center;">
    <div class="thumbnail" style="border:10px outset silver; height:420px;">
     <%=image_tag @current_user.avatar.url %>
     <br>
            <%= @current_user.company_name %>
      <div class="caption">
        <%= link_to "پروژه ها", projehabarayesherkat_profiles_path,:method => :get  %>
    </div>
  </div>
</div>
</div>
</div>
<div id="tab3">
      <div    style="direction: rtl;">
  <div style="text-align: center;">
    <div class="thumbnail" style="border:10px outset silver; height:420px;">
     <%=image_tag @current_user.avatar.url %>
     <br>
            <%= @current_user.company_name %>
      <div class="caption">
         <%= link_to "گزارش ها", reportbarayeproject_reports_path,:method => :get   %>
    </div>
  </div>
</div>
</div>
</div>
<div id="tab4">
      <div    style="direction: rtl;">
  <div style="text-align: center;">
    <div class="thumbnail" style="border:10px outset silver; height:420px;">
     <%=image_tag @current_user.avatar.url %>
     <br>
            <%= @current_user.company_name %>
      <div class="caption">
        <%= link_to "تماس با ما", new_contact_path,:method => :get   %>
    </div>
  </div>
</div>
</div>
</div>
</section>
</div>
        <script >
        $('.tabgroup > div').hide();
$('.tabgroup > div:first-of-type').show();
$('.tabs a').click(function(e){
  e.preventDefault();
    var $this = $(this),
        tabgroup = '#'+$this.parents('.tabs').data('tabgroup'),
        others = $this.closest('li').siblings().children('a'),
        target = $this.attr('href');
    others.removeClass('active');
    $this.addClass('active');
    $(tabgroup).children('div').hide();
    $(target).show();
  
})</script>

<div class="container">
            <div class="row wrap_9 wrap_4 wrap_10">
                <div class="grid_12">
                    <div class="header_1 wrap_3 color_3">
                        Get in Touch
                    </div>
                    <div class="box_3">
                        <ul class="list_1">
                            <li><a class="fa fa-twitter" href="#"></a></li>
                            <li><a class="fa fa-facebook" href="#"></a></li>
                            <li><a class="fa fa-google-plus" href="#"></a></li>
                            <li><a class="fa fa-pinterest" href="#"></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>