config/routes.rb
Rails.application.routes.draw do
  resources :userprojects

  resources :performs

  resources :contacts 

  resources :cities do 
    collection do
      get 'tehran'
      get 'esfahan'
      get 'ghom'
      get 'gilan'
      get 'golestan'
      get 'mazandaran'
      get 'kerman'
      get 'kermanshah'
      get 'azarbayjansharghi'
      get 'azarbayjangharbi'
      get 'ardebil'
      get 'eilam'
      get 'boushehr'
      get 'charmahalebakhtiari'
      get 'khorasanjounubi'
      get 'khorasanshomali'
      get 'khorasanrazavi'
      get 'khuzestan'
      get 'zanjan'
      get 'systanvabalouchestan'
      get 'semnan'
      get 'fars'
      get 'ghazvin'
      get 'kohgiluyevabayerahmad'
      get 'kordestan'
      get 'lorestan'
      get 'markazi'
      get 'hormozgan'
      get 'hamedan'
      get 'yazd'
      get 'alborz'
    end
  end

  devise_for :users

  resources :reports do
    collection do
      get 'reportbarayeproject'
    end
  end

  resources :profiles do
    collection do
      get 'mannagers'
      get 'ourprojects'
      get 'memari'
      get 'saze'
      get 'tasisat'
      get 'mohitezist'
      get 'tamasbama'
      get 'darbareyema'
      get 'taghdirname'
      get 'projehabarayesherkat'
      get 'newUser'
      post 'addUser'
      get 'editUser'
      put 'updateUser'
      patch 'updateUser'
    end
  end

  resources :profiles

  resources :projects
  resources :example_mailers

  root 'profiles#homepage'

  

end

app/models/userproject.rb
class Userproject < ActiveRecord::Base

	belongs_to :user
end

app/controllers/userprojects_controller.rb
class UserprojectsController < ApplicationController
  before_action :set_userproject, only: [:show, :edit, :update, :destroy]

  # GET /userprojects
  # GET /userprojects.json
  def index
    @userprojects = Userproject.all
  end

  # GET /userprojects/1
  # GET /userprojects/1.json
  def show
  end

  # GET /userprojects/new
  def new
    @userproject = Userproject.new
  end

  # GET /userprojects/1/edit
  def edit
  end

  # POST /userprojects
  # POST /userprojects.json
  def create
    @userproject = Userproject.new(userproject_params)

    respond_to do |format|
      if @userproject.save
        format.html { redirect_to @userproject, notice: 'Userproject was successfully created.' }
        format.json { render :show, status: :created, location: @userproject }
      else
        format.html { render :new }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userprojects/1
  # PATCH/PUT /userprojects/1.json
  def update
    respond_to do |format|
      if @userproject.update(userproject_params)
        format.html { redirect_to @userproject, notice: 'Userproject was successfully updated.' }
        format.json { render :show, status: :ok, location: @userproject }
      else
        format.html { render :edit }
        format.json { render json: @userproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userprojects/1
  # DELETE /userprojects/1.json
  def destroy
    @userproject.destroy
    respond_to do |format|
      format.html { redirect_to userprojects_url, notice: 'Userproject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userproject
      @userproject = Userproject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userproject_params
      params.require(:userproject).permit(:user_id, :project_id)
    end
end

app/helpers/userprojects_helper.rb
module UserprojectsHelper
end

app/views/userprojects/_form.html.erb
<%= form_for(@userproject) do |f| %>
  <% if @userproject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userproject.errors.count, "error") %> prohibited this userproject from being saved:</h2>

      <ul>
      <% @userproject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userprojects/edit.html.erb
<h1>Editing Userproject</h1>

<%= render 'form' %>

<%= link_to 'Show', @userproject %> |
<%= link_to 'Back', userprojects_path %>

app/views/userprojects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Userprojects</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userprojects.each do |userproject| %>
      <tr>
        <td><%= userproject.user_id %></td>
        <td><%= userproject.project_id %></td>
        <td><%= link_to 'Show', userproject %></td>
        <td><%= link_to 'Edit', edit_userproject_path(userproject) %></td>
        <td><%= link_to 'Destroy', userproject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userproject', new_userproject_path %>

app/views/userprojects/new.html.erb
<h1>New Userproject</h1>

<%= render 'form' %>

<%= link_to 'Back', userprojects_path %>

app/views/userprojects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @userproject.user_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @userproject.project_id %>
</p>

<%= link_to 'Edit', edit_userproject_path(@userproject) %> |
<%= link_to 'Back', userprojects_path %>