config/routes.rb
Rails.application.routes.draw do
  resources :userprojects

  resources :performs

  resources :contacts 

  resources :cities do 
    collection do
      get 'tehran'
      get 'esfahan'
      get 'ghom'
      get 'gilan'
      get 'golestan'
      get 'mazandaran'
      get 'kerman'
      get 'kermanshah'
      get 'azarbayjansharghi'
      get 'azarbayjangharbi'
      get 'ardebil'
      get 'eilam'
      get 'boushehr'
      get 'charmahalebakhtiari'
      get 'khorasanjounubi'
      get 'khorasanshomali'
      get 'khorasanrazavi'
      get 'khuzestan'
      get 'zanjan'
      get 'systanvabalouchestan'
      get 'semnan'
      get 'fars'
      get 'ghazvin'
      get 'kohgiluyevabayerahmad'
      get 'kordestan'
      get 'lorestan'
      get 'markazi'
      get 'hormozgan'
      get 'hamedan'
      get 'yazd'
      get 'alborz'
    end
  end

  devise_for :users

  resources :reports do
    collection do
      get 'reportbarayeproject'
    end
  end

  resources :profiles do
    collection do
      get 'mannagers'
      get 'ourprojects'
      get 'memari'
      get 'saze'
      get 'tasisat'
      get 'mohitezist'
      get 'tamasbama'
      get 'darbareyema'
      get 'taghdirname'
      get 'projehabarayesherkat'
      get 'newUser'
      post 'addUser'
      get 'editUser'
      put 'updateUser'
      patch 'updateUser'
    end
  end

  resources :profiles

  resources :projects
  resources :example_mailers

  root 'profiles#homepage'

  

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :project
	
has_attached_file :document
validates_attachment :document, :content_type => { :content_type => ["application/pdf", "application/zip", "application/x-zip", "application/x-zip-compressed","application/octet-stream"] }
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # load_and_authorize_resource 
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reports
  # GET /reports.json
  def index
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
    @projects_name = []
    @projects = current_user.nazer_projects.all
    @projects.each do |p|
    @projects_name << p.name
    end
  end

  # GET /reports/new
  def new
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
    @projects_name = []  
    @report = Report.new
    @projects =  current_user.nazer_projects.all
    @projects.each do |p|
    @projects_name << p.name
      if not p.nil?
        @projects_name << p
      end
    end
  end

  # GET /reports/1/edit
  def edit
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save


        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    if current_user.role == "کارفرما"
      redirect_to root_url
    end
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def reportbarayeproject
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name_project, :description, :title_report, :subject, :document , :project_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div style="height:1000px">
                      
                         
      <h1 style="margin-left:50%"> فرم ایجاد گزارش </h1>
                      <div class="portlet-body form register span6">
                        <!-- BEGIN FORM-->
                      <%= form_for(@report) do |f| %>
                        <% if @report.errors.any? %>
                          <div id="error_explanation">
                            <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

                            <ul>
                            <% @report.errors.full_messages.each do |message| %>
                              <li><%= message %></li>
                            <% end %>
                            </ul>
                          </div>
                        <% end %>
                        <!-- <form > -->
                          <div class="form-body">
                            <div class="form-group">
                              <p class="contact"><label class="control-label">نام پروژه</label></p>
                              <select name="report[name_project]">
                              <%#byebug%>
                                <%current_user.nazer_projects.all.each do |p| %>
                                
                                  <%if not p.nil? %>
                                    <option value="<%=p.name%>"><%=p.name%></option>
                                  <%end%>
                                <%end%>
                              </select>
                              <%#= f.select :user_id, select_tag(:user_id, @profiles_name) %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>
                            <div class="form-group">
                              <p class="contact"><label class="control-label">عنوان گزارش</label></p>
                              <%= f.text_field :title_report , class: "form-control"  ,placeholder:"عنوان گزارش" %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                             <p class="contact"> <label class="control-label"> قسمت مربوطه: </label></p>
                              <%= f.text_field :subject , class: "form-control"   %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>

                            <div class="form-group">
                             <p class="contact"> <label class="control-label">توضیحات</label></p>
                              <%=  f.text_area :description , class: "form-control"   %>
<!--                               <input type="text" class="form-control" placeholder="Enter text"> -->
                            </div>




                            <div class="form-group">
                              <p class="contact"><label class="control-label" >آپلود گزارش</label></p>
                              <%= f.file_field :document ,class: "form-control spinner" %>
                              <!-- <input type="password" class="form-control spinner" placeholder="Password"> -->
                            </div>
                            
                            <!-- <div class="form-group last">
                              <label class="control-label">Static Control</label>
                              <p class="form-control-static">
                                 email@example.com
                              </p>
                            </div> -->
                          </div>
                          <div class="form-actions right">
                          <%= f.submit  "ایجاد گزارش" ,style: "width:24%;background-color:#8e5fa2;color:white;line-height:191%;" , class: "btn-md"%>
<!--                             <button type="submit" class="btn green">Submit</button>
                            <button type="button" class="btn default">Cancel</button> -->
                          </div>
                          <% end %>
                        <!-- </form> -->
                        <!-- END FORM-->
                      </div>
</div>

<style type="text/css">
  
  /*
http://www.freshdesignweb.com/beautiful-registration-form-with-html5-and-css3.html
*/

.form{
  background:#f1f1f1; width:470px; margin:0 auto; padding-left:50px; padding-top:20px;
}
.form fieldset{border:0px; padding:0px; margin:0px;}
.form p.contact { font-size: 12px; margin:0px 0px 10px 0;line-height: 14px; font-family:Arial, Helvetica;}

.form input[type="text"] { width: 400px; }
.form input[type="email"] { width: 400px; }
.form input[type="password"] { width: 400px; }
.form input.birthday{width:60px;}
.form input.birthyear{width:120px;}
.form label { color: #000; font-weight:bold;font-size: 12px;font-family:Arial, Helvetica; }
.form label.month {width: 135px;}
.form input, textarea { background-color: rgba(255, 255, 255, 0.4); border: 1px solid rgba(122, 192, 0, 0.15); padding: 7px; font-family: Keffeesatz, Arial; color: #4b4b4b; font-size: 14px; -webkit-border-radius: 5px; margin-bottom: 15px; margin-top: -10px; }
.form input:focus, textarea:focus { border: 1px solid #ff5400; background-color: rgba(255, 255, 255, 1); }
.form .select-style {
  -webkit-appearance: button;
  -webkit-border-radius: 2px;
  -webkit-box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.1);
  -webkit-padding-end: 20px;
  -webkit-padding-start: 2px;
  -webkit-user-select: none;
  background-image: url(images/select-arrow.png), 
    -webkit-linear-gradient(#FAFAFA, #F4F4F4 40%, #E5E5E5);
  background-position: center right;
  background-repeat: no-repeat;
  border: 0px solid #FFF;
  color: #555;
  font-size: inherit;
  margin: 0;
  overflow: hidden;
  padding-top: 5px;
  padding-bottom: 5px;
  text-overflow: ellipsis;
  white-space: nowrap;}
.form .gender {
  width:410px;
  }
.form input.buttom{ background: #4b8df9; display: inline-block; padding: 5px 10px 6px; color: #fbf7f7; text-decoration: none; font-weight: bold; line-height: 1; -moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 5px; -moz-box-shadow: 0 1px 3px #999; -webkit-box-shadow: 0 1px 3px #999; box-shadow: 0 1px 3px #999; text-shadow: 0 -1px 1px #222; border: none; position: relative; cursor: pointer; font-size: 14px; font-family:Verdana, Geneva, sans-serif;}
.form input.buttom:hover  { background-color: #2a78f6; }

.container_25{
  width: 100%;
  height: 100%;
  position: relative;
}
.clr{
  clear: both;
}
.container_25 > header{
  padding: 20px 30px 20px 30px;
  margin: 0px 20px 10px 20px;
  position: relative;
  display: block;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.2);
    text-align: center;
}
.container_25 > header h1{
  position: relative;
  color: #498ea5;
  font-weight: 700;
  font-style: normal;
  font-size: 30px;
  padding: 0px 0px 5px 0px;
  text-shadow: 0px 1px 1px rgba(255,255,255,0.8);
}
.container_25 > header h1 span{
  font-family: 'Alegreya SC', Georgia, serif;
  font-size: 20px;
  line-height: 20px;
  display: block;
  font-weight: 400;
  font-style: italic;
  color: #719dab;
  text-shadow: 1px 1px 1px rgba(0,0,0,0.1);
}
.container_25 > header h2{
  font-size: 16px;
  font-style: italic;
  color: #2d6277;
  text-shadow: 0px 1px 1px rgba(255,255,255,0.8);
}

</style>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>


  <h1 style="margin-right:5%">لیست گزارش ها</h1>

<div class="page-wrap" style="height:1000px;">
                <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th >
                     لینک دانلود گزارش
                  </th>
                  <th>
                     موضوع گزارش
                  </th>
                  
                 <th>
                     نام پروژه
                  </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                <% @reports.each do |report| %>
                <tr>
                <th ><%= report.name_project %></td>
                <th ><%= report.title_report%></td>
                <th >  <%= link_to "دانلود فایل", report.document.url, target: "_blank" %></td>
                <th ><%= link_to 'جزئيات بیشتر', report , class:"btn btn-sh green hidden-print margin-bottom-5"%></td>
                <th ><%= link_to 'ویرایش', edit_report_path(report) , class:"btn btn-sh blue hidden-print margin-bottom-5" %></td>
                <% if current_user.role == "ادمین"%>
                <th ><%= link_to 'حذف', report, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-sh red hidden-print margin-bottom-5" %></td>
                <%end%>
      </tr>
    <% end %>
                </tr>
                </tbody>
                </table>
                <%= link_to 'ایجاد گزارش', new_report_path ,class:"action-button shadow animate green" %>
              </div>


<br>


<style>
  #page-wrap {
    align:right;
  margin: 50px;
}


  /* 
  Generic Styling, for Desktops/Laptops 
  */
  #FU {
    margin-right: 10%;
  }
  table { 
    width: 100%; 
    border-collapse: collapse; 
  }
  /* Zebra striping */
  tr:nth-of-type(odd) { 
    background: #eee; 
  }
  th { 
    background: #333; 
    color: white; 
    font-weight: bold; 
  }
  td, th { 
    padding: 6px; 
    border: 1px solid #ccc; 
    text-align: right; 
  }
  /* 
  Max width before this PARTICULAR table gets nasty
  This query will take effect for any screen smaller than 760px
  and also iPads specifically.
  */
  @media 
  only screen and (max-width: 760px),
  (min-device-width: 768px) and (max-device-width: 1024px)  {
  
    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr { 
      display: block; 
    }
    
    /* Hide table headers (but not display: none;, for accessibility) */
    thead tr { 
      position: absolute;
      top: -9999px;
      left: -9999px;
    }
    
    tr { border: 1px solid #ccc; }
    
    td { 
      /* Behave  like a "row" */
      border: none;
      border-bottom: 1px solid #eee; 
      position: relative;
      padding-left: 50%; 
    }
    
    td:before { 
      /* Now like a table header */
      position: absolute;
      /* Top/left values mimic padding */
      top: 6px;
      left: 6px;
      width: 45%; 
      padding-right: 10px; 
      white-space: nowrap;
    }
    
    /*
    Label the data
    */
  
  }
  
  /* Smartphones (portrait and landscape) ----------- */
  @media only screen
  and (min-device-width : 320px)
  and (max-device-width : 480px) {

  
  /* iPads (portrait and landscape) ----------- */

  }
  
  </style>
  

app/views/reports/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/reportbarayeproject.html.erb
<style>
  #page-wrap {
    align:right;
  margin: 50px;
  }


  /* 
  Generic Styling, for Desktops/Laptops 
  */
  #FU {
    margin-right: 10%;
  }
  table { 
    width: 100%; 
    border-collapse: collapse; 
  }
  /* Zebra striping */
  tr:nth-of-type(odd) { 
    background: #eee; 
  }
  th { 
    background: #333; 
    color: white; 
    font-weight: bold; 
  }
  td, th { 
    padding: 6px; 
    border: 1px solid #ccc; 
    text-align: right; 
  }
  /* 
  Max width before this PARTICULAR table gets nasty
  This query will take effect for any screen smaller than 760px
  and also iPads specifically.
  */
  @media 
  only screen and (max-width: 760px),
  (min-device-width: 768px) and (max-device-width: 1024px)  {
  
    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr { 
      display: block; 
    }
    
    /* Hide table headers (but not display: none;, for accessibility) */
    thead tr { 
      position: absolute;
      top: -9999px;
      left: -9999px;
    }
    
    tr { border: 1px solid #ccc; }
    
    td { 
      /* Behave  like a "row" */
      border: none;
      border-bottom: 1px solid #eee; 
      position: relative;
      padding-left: 50%; 
    }
    
    td:before { 
      /* Now like a table header */
      position: absolute;
      /* Top/left values mimic padding */
      top: 6px;
      left: 6px;
      width: 45%; 
      padding-right: 10px; 
      white-space: nowrap;
    }
    
    /*
    Label the data
    */
  
  }
  
  /* Smartphones (portrait and landscape) ----------- */
  @media only screen
  and (min-device-width : 320px)
  and (max-device-width : 480px) {

  
  /* iPads (portrait and landscape) ----------- */

  }
  
  </style>

<p id="notice"><%= notice %></p>
  <h1 style="margin-right:5%">لیست گزارش ها</h1>

<div class="col-xs-12">
                <table class="table table-striped table-hover">
                <thead>
                <tr>
                  <th >
                     لینک دانلود گزارش
                  </th>
                  <th>
                     موضوع گزارش
                  </th>
                  
                 <th>
                     نام پروژه
                  </th>
                </tr>

                </thead>
                <tbody>
                <tr>
                <%#byebug%>
                <% current_user.projects.all.each do |proj| %>
                <%#byebug%>
                  <%proj.reports.all.each do |report|%>
                <tr>
                <th ><%= proj.name %></td>
                <th ><%= report.title_report%></td>
                <th >  <%= link_to "دانلود فایل", report.document.url, target: "_blank" , style: "color:blue; text-decoration:none;"%></td>
                <th ><%= link_to 'جزئيات بیشتر', report , class:"btn btn-sh green hidden-print margin-bottom-5"%></td>
                <th ><%= link_to 'ویرایش', edit_report_path(report) , class:"btn btn-sh blue hidden-print margin-bottom-5" %></td>
                <% if current_user.role == "ادمین"%>
                <th ><%= link_to 'حذف', report, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-sh red hidden-print margin-bottom-5" %></td>
                <%end%>

                </tr>
              <% end %>
              <% end %>
                </tr>
                </tbody>
                </table>
              </div>


<br><br><br><br>
<%if not current_user.nil? and current_user.role == 'ناظر' %>
<%= link_to 'ایجاد گزارش', new_report_path ,class:"btn btn-sh green hidden-print margin-bottom-5",style:"margin-right:5%;margin-bottom:2%"%>
<%end%>
<br><br><br><br>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<section id="pricing-table">
            <div class="container">
                <div class="row">
                    <div class="pricing">
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <div class="pricing-table">
                                <div class="pricing-header">
                                    <p class="pricing-title">
                                      <%= @report.name_project %>

                                    </p>
                                </div>

                                <div class="pricing-list">
                                    <ul>
                                    <%#byebug%>
                                        <li><strong>name project:</strong>
                                        <%= @report.name_project %></li>
                                        <li><span>description:</span>   <strong></strong>
                                        <%= @report.description %></li>
                                        <li><span>subject:</span> <strong></strong>
                                        <%= @report.subject %></li>
                                        <li><strong>document:</strong><%= link_to "My document", @report.document.url, target: "_blank" %>
</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>



<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>


<style type="text/css">
  
  /*Font Loded*/
@import url(http://fonts.googleapis.com/css?family=Roboto:400,700);
.btn-custom {
  color: #bdc3c7;
  font-size: 18px;
  border: 1px solid #bdc3c7;
}
.btn-custom:hover {
  color: #ffffff;
  border: 1px solid #ffffff;
}
#pricing-table {
  padding-top: 50px;
}
#pricing-table .pricing {
  marign: 0;
  padding: 0;
  font-family: 'Robot', sans-serif;
}
#pricing-table .pricing .pricing-table {
  padding-bottom: 30px;
}
#pricing-table .pricing .pricing-table .pricing-header {
  position: relative;
  background: #34495e;
  padding: 22px 22px;
  text-align: center;
  border-top-right-radius: 4px;
  border-top-left-radius: 4px;
}
#pricing-table .pricing .pricing-table .pricing-header .pricing-title {
  color: #ffffff;
  text-transform: uppercase;
  letter-spacing: 2px;
  font-size: 24px;
  text-align: center;
  font-weight: 700;
}
#pricing-table .pricing .pricing-table .pricing-header .pricing-rate {
  font-size: 70px;
  font-weight: 700;
  color: #ffffff;
  position: relative;
  text-align: center;
}
#pricing-table .pricing .pricing-table .pricing-header .pricing-rate sup {
  font-size: 24px;
  position: relative;
  top: -30px;
  color: #bdc3c7;
}
#pricing-table .pricing .pricing-table .pricing-header .pricing-rate span {
  font-size: 16px;
  color: #bdc3c7;
  text-transform: uppercase;
}
#pricing-table .pricing .pricing-list {
  padding: 20px 0 40px 0;
  background: #ffffff;
  border: 1px solid #e3e3e3;
}
#pricing-table .pricing .pricing-list ul {
  padding: 0px;
  display: table;
  margin: 0px auto;
}
#pricing-table .pricing .pricing-list ul li {
  list-style: none;
  border-bottom: 1px solid #EAECEB;
  color: #bdc3c7;
  font-size: 16px;
  line-height: 42px;
}
#pricing-table .pricing .pricing-list ul li:last-child {
  border: none;
}
#pricing-table .pricing .pricing-list ul li i {
  margin-right: 12px;
  color: #bdc3c7;
}
#pricing-table .pricing .pricing-list ul li span {
  color: #34495e;
}
</style>